# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flowstate/client/v1/client.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'flowstate/client/v1/client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flowstate.v1 import state_pb2 as flowstate_dot_v1_dot_state__pb2
from flowstate.v1 import commands_pb2 as flowstate_dot_v1_dot_commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n flowstate/client/v1/client.proto\x12\x13\x66lowstate.client.v1\x1a\x18\x66lowstate/v1/state.proto\x1a\x1b\x66lowstate/v1/commands.proto\"Q\n\x0e\x45xecuteRequest\x12?\n\rstate_context\x18\x01 \x01(\x0b\x32\x1a.flowstate.v1.StateContextR\x0cstateContext\"\x86\x01\n\x0f\x45xecuteResponse\x12?\n\rstate_context\x18\x01 \x01(\x0b\x32\x1a.flowstate.v1.StateContextR\x0cstateContext\x12\x32\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x18.flowstate.v1.AnyCommandR\x07\x63ommand2g\n\rClientService\x12V\n\x07\x45xecute\x12#.flowstate.client.v1.ExecuteRequest\x1a$.flowstate.client.v1.ExecuteResponse\"\x00\x42\x94\x01\n\x17\x63om.flowstate.client.v1B\x0b\x43lientProtoP\x01\xa2\x02\x03\x46\x43X\xaa\x02\x13\x46lowstate.Client.V1\xca\x02\x13\x46lowstate\\Client\\V1\xe2\x02\x1f\x46lowstate\\Client\\V1\\GPBMetadata\xea\x02\x15\x46lowstate::Client::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flowstate.client.v1.client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.flowstate.client.v1B\013ClientProtoP\001\242\002\003FCX\252\002\023Flowstate.Client.V1\312\002\023Flowstate\\Client\\V1\342\002\037Flowstate\\Client\\V1\\GPBMetadata\352\002\025Flowstate::Client::V1'
  _globals['_EXECUTEREQUEST']._serialized_start=112
  _globals['_EXECUTEREQUEST']._serialized_end=193
  _globals['_EXECUTERESPONSE']._serialized_start=196
  _globals['_EXECUTERESPONSE']._serialized_end=330
  _globals['_CLIENTSERVICE']._serialized_start=332
  _globals['_CLIENTSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
